symlink:
  - README.md: README.tpl.md
  - .neat.yml: .neat.tpl.yml

ask:
  - id: repo
    description: What is the uri of this Neat repo? In the format GitHubUsername/repo (or the name you added to the Neat registered repos)
    pattern: 'make your own repo a Neat template'
  - id: purpose
    description: What is the purpose of this repo? What will people achieve when using it?

inject:
  - id: neat-usage
    file: inject/neat-usage.md
    target: README.md

ignore: [inject]
